Made up tableView with 20 mock-images
DmitriiMM/ImageFeed pull request #1
Opened 2022-11-26 22:38 UTC by DmitriiMM

2022-11-27 09:09 UTC, mmbabaev commented
<img width="652" alt="Screen Shot 2022-11-27 at 12 07 40" src="https://user-images.githubusercontent.com/12600807/204127336-60762386-8851-493d-8745-1444aef7bf1d.png">
поставили расстояния 8 до margins, а не края ячейки. Из-за этого расстояние больше, чем нужно

2022-11-27 09:32 UTC, mmbabaev requested changes

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        self.gradientViewCell = nil
давайте здесь не удалять ссылку на `gradientViewCell`, а очищать `gradientViewCell.layer.sublayers`. 

Сейчас программа работает корректно, но способ обработки переиспользования не очень хороший. 
1) Мы добавляем слой на вью для градиента
2) Переиспользуем ячейку
3) Удаляем ссылку на вью для градиента 
4) слой-градиет создается, но не присваивается вью для градиента, там остается старый (первый) слой

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        self.gradientViewCell = nil
Если конфигурация слоев разная для разных ячеек, то этот способ не будет работать

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        self.gradientViewCell = nil
Другой способ - создавать и добавлять слой один раз при инициализации ячейки, затем только конфигурировать этот слой

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        if #available(iOS 15, *) {
для ios 13 и 14 дата не выставляется

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        let layer0 = CAGradientLayer(layer: cell.gradientViewCell as Any)
плохой нейминг слоя

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        let layer0 = CAGradientLayer(layer: cell.gradientViewCell as Any)
Не нужно использовать этот инициализатор слоя, он используется для другого. 
Просто создайте `CAGradientLayer()`

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        cell.gradientViewCell?.layer.addSublayer(layer0)
так у вас слой накладывается сверху на слой label

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        cell.gradientViewCell?.layer.addSublayer(layer0)
и текст становится серым

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        layer0.locations = [0, 1]
сможете пожалуйста объяснить для чего добавлены свойства на строчках 45-48? Сходу не смог разобраться

2022-11-27 09:32 UTC, mmbabaev commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private var photosName = [String]()
Знаю, что по учебнику, но я бы называл `photosName` -> `photoNames`

2022-11-27 16:23 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        layer0.locations = [0, 1]
Объяснить не смогу)) Весь код касаемо градиента я скопировал из фигмы и наощупь что-то попытался поменять чтоб работало более менее как мне надо) то что текст темнеет честно не заметил даже. Буду дальше разбираться

2022-11-27 20:43 UTC, DmitriiMM commented
Мелочные замечания поправил, не могу разобраться с градиентом. Если правильно понял CAGradientLayer в принципе не самое удачное решение так как этот класс для анимированного градиента. 
Подскажите пожалуйста какие пути решения еще можно выбрать и как все таки грамотно доделать с помощью CAGradientLayer?

2022-11-27 20:46 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        cell.gradientViewCell?.layer.addSublayer(layer0)
Вот это кстати совсем непонятно почему происходит, потому что в иерархии лейбл рисует выше подкрашенной вьюшки

2022-11-29 07:21 UTC, mmbabaev commented
CAGradientLayer в принципе норм. Чтобы обойти проблему с затемнением, можно использовать добавлять слой на индекс 0: https://developer.apple.com/documentation/quartzcore/calayer/1410944-insertsublayer

2022-11-29 12:26 UTC, DmitriiMM commented
подсказка с insertSublayer(_:at:) очень помогла, но что-то сломалось с переиспользованием ячеек. не могу понять причину так как градиент присваивается в тех же местах что лейбл и картинки, но почему то даты и картинки отрабатывают на каждую ячейку а gradientLayer на последнюю отрисованную

2022-11-29 12:29 UTC, DmitriiMM commented
Пока подбирал слова к предыдущему комменту, понял в чем ошибка. инициализацию  let gradientLayer = CAGradientLayer() перенес в функцию конфигурации градиента и это заработало))

2022-11-30 13:45 UTC, mmbabaev commented
Сейчас слои создаются новые, добавляются при переиспользовании.Если мотать туда-сюда, то можно достичь такого эффекта. Создавайте слой градиента один раз в ячейке

```
final class ImagesListCell: UITableViewCell {
    static let reuseIdentifier = "ImagesListCell"

   let gradientLayer = CAGradientLayer()
```
![Screen Shot 2022-11-30 at 16 40 15](https://user-images.githubusercontent.com/12600807/204812165-514ba5c6-8876-4a3f-8b86-1c2f7bbeafda.png)

2023-01-27 18:17 UTC, merged