Add detailVC and profileVC
DmitriiMM/ImageFeed pull request #2
Opened 2022-12-05 20:56 UTC by DmitriiMM

2022-12-05 21:32 UTC, ABashkirova requested changes
Комментарий на платформе

2022-12-05 21:32 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let viewController = segue.destination as! SingleImageViewController
Так делают в продакшене, это в пределах нормы. Но лично мне такой код очень не нравится, я бы переписала в безопасном разыменовывании

2022-12-05 21:32 UTC, ABashkirova commented on ImageFeed/Info.plist
> +	<string>Allow access to photo library</string>
зачем?

2022-12-05 21:32 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +    }()
передавать ссылку на себя в кнопку – не очень классно, Xcode даже ругается. В таких случаях лучше сделать lazy свойсвто
```suggestion
    private lazy var logoutButton: UIButton = {
        let image = UIImage(systemName: "ipad.and.arrow.forward")!
        let button = UIButton.systemButton(
            with: image,
            target: self,
            action: #selector(logOutButtonTapped)
        )
        button.tintColor = UIColor(named: "YP Red")
        return button
    }()
```

2022-12-05 21:32 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +    func  addSubViews() {
```suggestion
    func addSubViews() {
```

2022-12-05 21:32 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +    @objc func logOutButtonTapped(_ sender: Any) {}
не забывай приватить и пробельчики :) 
```suggestion
    @objc func logOutButtonTapped(_ sender: Any) { }
```

2022-12-05 21:32 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +    func addConstraints() {
нужно заприватить

2022-12-05 21:32 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +    var image: UIImage!{
```suggestion
    var image: UIImage! {
```

2022-12-05 21:32 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +        let ac = UIActivityViewController(activityItems: [image], applicationActivities: nil)
давай заприватим

2022-12-05 21:41 UTC, DmitriiMM commented on ImageFeed/Info.plist
> +	<string>Allow access to photo library</string>
Чтобы появилась кнопка сохранения в Фотографии. В задание сформулировано как-то двусмысленно. То ли от кнопки должно просто выезжать меню "поделиться", то ли нужно добавить  дополнительные кнопки share. Я нашел инфу и добавил сохранение в галерею таким образом.

2022-12-06 15:30 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let viewController = segue.destination as! SingleImageViewController
Правильно понимаю что достаточно заменить "as!" на "as?"?

2022-12-06 20:06 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let viewController = segue.destination as! SingleImageViewController
Да, можно вот так, в иф добавить:
 if segue.identifier == showSingleImageSegueIdentifier, 
    let viewController = segue.destination as? SingleImageViewController { 
... 
}

2023-01-27 18:24 UTC, merged