Sprint 12
DmitriiMM/ImageFeed pull request #8
Opened 2023-02-08 21:50 UTC by DmitriiMM

2023-02-09 11:13 UTC, ABashkirova requested changes
Где-то в фетч профайле не правильная последовательность скрытия/показа алерта на ошибку, надо пофиксить. 
<img width="487" alt="Снимок экрана 2023-02-09 в 13 40 15" src="https://user-images.githubusercontent.com/20269264/217803088-969e59b7-28ac-4e63-bf8e-6f48d5f9bfd0.png">

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/Auth/OAuth2TokenStorage.swift
>              KeychainWrapper.standard.set(token, forKey: Keys.token.rawValue)
Здесь нужно написать If let и обработать второй сценарий для опционала

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/Auth/WebViewViewController.swift
> +    static func clean() {
Здесь рекомендую код вынести в отдельный сервис. Статические методы, глобальный контекст в продакшене не используют. Если этот код был дан в учебнике, то чисто ради упрощения понимания. 

На вью контроллере такую логику обычно не оставляют

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
>  final class ImagesListCell: UITableViewCell {
мне не хватает здесь описанной логики setIsLiked, надо доработать

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    let gradientButtomCell = CAGradientLayer()
https://sarunw.com/posts/spell-checking-in-xcode/ – настраиваем проверку правописания и не делаем опечатки в работах

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +        lastLoadedPage = lastLoadedPage == nil ? 1 : nextPage
в названии переменной lastLoadedPage не зря используется глагол прошедшего времени. Последняя **загруженная** страница. Обновлять это свойство имеет смысл, когда мы загрузили страницу

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +            DispatchQueue.main.async { [weak self] in
на сколько я понимаю, session.objectTask - все полученные ответы уже переводит на  DispatchQueue.main.async. Поэтому тут это делать избыточно

session.objectTask - это такой лайфхак, чтобы не задумываться перевел ли ты на главную очередь или нет, и минимизировать ошибки. 

Однако это холиварный вопрос, потому что никакого UI-кита, главных очередей в сетевом слое не должно быть. То есть лучше делать переход на главную очередь тогда, когда собираешься обновлять UI. В остальных случаях - оставить как есть/перенести на другой бекграунд поток

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        let onePhoto = Photo(photoResult: photo)
круто что добавил свой инициализатор :)

я предпочитаю решать задачу с другого конца, транспортному объекту (PhotoResult) дописывать функцию convertToViewModel. И делать это в приватном расширнеии рядом с сетевым кодом (то есть с этим сервисом).

Тогда код можно написать в функциональном виде:
var photosArray: [Photo] = photoResult.map { $0.convertToViewModel() }

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +        task.resume()
session.objectTask уже сделал resume, повторная операция может приводить к ошибкам

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +}
Не плохо бы модели хранить в своих файлах

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        case false:
ну нет, swift не для этого вырос, чтобы true-false разбирать))

давай либо if-else либо тернарником воспользуемся

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                UIBlockingProgressHUD.dismiss()
чтобы не повторяться, можно вынести за скобки switch result

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            case .failure(_):
```suggestion
            case .failure:
```

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                break
break нужен, если ты не хочешь обрабатывать кейс, и тут он избыточен, потому что ты что-то на этот кейс сделал

2023-02-09 11:13 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +        let url = URL(string: fullImageUrl!)
а если ошибка в ссылке? будем крашиться в проде. Давай напишем безопасную конструкцию

2023-02-09 17:00 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListService.swift
> +            DispatchQueue.main.async { [weak self] in
Вот тут совсем вас не понял. session.objectTask - это лайфхак, чтобы уйти от дублирования кода, как я понял в контексте учебника. 
строку 29 - /DispatchQueue.main.async { [weak self] in/ удалил. Понятно да, в чем излишне.

2023-02-09 17:05 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        let onePhoto = Photo(photoResult: photo)
Спасибо за этот комментарий. Я долго искал решение и нашел через инициализатор. Могу оставить свой код? Вашим способом обязательно воспользуюсь в следующей аналогичной задаче.

2023-02-09 17:28 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +            DispatchQueue.main.async { [weak self] in
Он не только от дублирования спасает, но еще переводит на главную очередь. 

Поэтому дополнительно да, переводить на главную очередь не нужно. 

Но я подсвечиваю холиварность этого лайфхака в том месте, что он не должен возвращать на главный поток (на мой взгляд), потому что для сетевого сервиса это не та зона ответсвенности. 

Если не понятно – переформулируй вопрос

2023-02-09 18:26 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        case false:
Я прям расхохотался)) Когда писал это, подумал, что вот какой я молодец, стараюсь писать везде через свич :D

2023-02-09 18:46 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        case false:
switch *

2023-02-09 18:47 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        case false:
это тоже моя любимая конструкция, но здесь она не уместна

2023-02-09 18:48 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        let onePhoto = Photo(photoResult: photo)
да, конечно

2023-02-09 19:20 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListService.swift
> +            DispatchQueue.main.async { [weak self] in
То есть если на практике то внутри функции objectTask логичнее будет удалить DispatchQueue.main.async на 13ой строке и уже в других файлах обращаться к objectTask из главной очереди?

2023-02-09 19:23 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        let onePhoto = Photo(photoResult: photo)
А с DateFormatter также нельзя поступить? Разве мой способ хуже? Или вся загвоздка именно в соответствии ТЗ?

2023-02-09 21:43 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +            DispatchQueue.main.async { [weak self] in
Да, причем чем ближе к ui тем лучше.

Но тут надо быть осторожным, так как использованный KVO должен тоже на главной работать 

Не рекомендую править сейчас, но можно дополнительно поупражняться после окончания модуля

2023-02-09 21:48 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        let onePhoto = Photo(photoResult: photo)
ТЗ - часть договоренностей, которые надо выполнять, либо _аргументированно_ договариваться

По Дейт форматтеру, я согласна что твое решение рабочее и еще совсем недавно все так и писали. 
Однако надо стремиться использовать подходящие инструменты для своих задач, и тут я с авторами согласна, новый форматтер лаконичнее справляется с задачей. (Про неподходящее обычно шутят "микроскопом гвозди забивать")

Ты молодец, что нашел решение, предлагаю тебе сравнить с тем, что предлагают авторы, и понять почему оно лучше.

https://sarunw.com/posts/how-to-parse-iso8601-date-in-swift/

2023-02-09 21:52 UTC, ABashkirova commented
@DmitriiMM 

Я была не корректна, когда упомянула документацию unsplash и опциональные свойства.
Действительно там такого нет. А на деле есть

Мне очень жаль, что этот момент не зафиксирован в документации 🥲 так всегда, только попытным путем достигается правда


Давай как минимум попробуем профиксить поле bio, если с остальными не удается 👌

2023-02-09 22:04 UTC, DmitriiMM commented
Я устранил все замечания и готов отправлять на повторную проверку, но раз уж диалог, то уточню. Сделал все свойства опциональными и Парсинг через try?. Теперь со входом проблем не возникает. 
У меня еще вопрос по токену. Вы написали что =nil не дает нужного результата. Я проверил через print(). Результат token = nil. Правда в сеттер добавил блок else. Возможно с ним токен получается "занилить"

2023-02-09 22:10 UTC, ABashkirova commented
1. Парсинг можно и через optional try, хотя по идее никакого ручного декодинга делать не надо, если структура Codable и ключи совпадают 

2. Да, именно из-за отсутствия блока else токен не должен был обнуляться

2023-02-10 19:30 UTC, ABashkirova requested changes

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
>              UIBlockingProgressHUD.dismiss()
Здесь  DispatchQueue.main.async  лишний 

UIBlockingProgressHUD.dismiss() - внутри failure тоже лишний

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
>      var image: UIImage! {
Новый код не учитывает, что нужно подготовить изображение для share кнопки. Функция сломана, так как в момент вызова  `let ac = UIActivityViewController(activityItems: [image], applicationActivities: nil)` image всегда nil

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +        authViewController.modalPresentationStyle = .fullScreen
Роутинг на авторизацию не даст повторно авторизоваться, так как за дальнейшую навигацию будет отвечать делегат AuthViewController – SplashVC, делегат nil, некому обрабатывать навигацию. 

В чеклисте кстати про это было сказано:

>  `rootViewController` заменяется на `SplashViewController`

>

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/Profile/ProfileViewController.swift
> +    let gradientChangeAnimation = CABasicAnimation(keyPath: "locations")
Давай проверим во всех классах уровень доступа у переменных

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/PhotoModel.swift
> +    var likedPhoto: PhotoResult
будет меняться? не стоит ли let сделать?

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        animationLayers.insert(gradientForCell)
зачем промежуточно сохранять?

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    private func addForGradient(on superView: UIImageView) -> CAGradientLayer {
`private func addForGradient(on superView: UIImageView) -> CAGradientLayer `

С назначением функции есть несколько проблем:

- Она возвращает результат – ок, значит ожидаю что она создает слой и его возвращает. 
- На деле же, она его еще сохраняет в локальный стейт (animationLayers), и устанавливается на изображение в superView.layer 

Обычно разделяют эти шаги, одно место чтобы создать, другое, чтобы обвесить вью новым поведением (слой, анимация). 

Иначе просто приходится копаться в не переиспользуемом коде и задумываться о его истинном назначении. Тем более, легко забыть/не заметить, что она слой складывает на элемент, а это значит что про этот слой надо где-то в другом месте думать/удалять. 

Здесь я бы попробовала поделить логику на отдельные части. 
Ну и кажется, стоит все это делать в коде для ячейки, а не в классе списка

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
>          }
Это код дублируется, здесь if-else, в ячейке switch. Надо бы использовать уже подготовленную функцию под эту задачу

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        cell.gradientBottomCell.isHidden = true
Круто что подумал, что эти элементы на ячейке не должны присуствовать. 
Однако, мне кажется это избыточным, если есть возможность слой поверх элементов положить. Почему бы так не сделать?

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    var photos: [Photo] = []
Я замечаю баг, но не могу понять в чем проблема:

1. Отметить лайком изображение, дождаться ответа
2. Открыть изображение в отдельном окне
3. Нажать назад

Изображение скидывает новый стейт лайка, как будто где-то хранится старое состояние. Будет здорово, если отловишь этот бажок

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        self.photos.insert(photo, at: index)
:)

self.photo[index] = photo

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +        let task = session.objectTask(for: request) { [weak self] (result: Result<LikedPhotoResult, Error>) in
таска сохраняется, но дальше ни где не используется. Можно наверное опустить, чтобы ворнинг приглушить
```suggestion
        session.objectTask(for: request) { [weak self] (result: Result<LikedPhotoResult, Error>) in
```

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListService.swift
> +        task.resume()
надо бы удалить, нет?

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        }
:)

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    }
этот метод прекрасен, чтобы удалить лишние анимации, сбросить стейт кнопки лайк, то есть подготовиться для настройки новыми данными. 

Иначе при быстром скроле можно будет заметить оставшиеся старые картинки :) правда на не очень быстрых девайсах)

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                cell.imageCell.kf.indicatorType = .none
этот комплишен сильно захватывает ссылку на cell. Потому может делать что попало с его сабвьюшками. 

Изображение грузится достаточно долго, пока ты листаешь список, ячейка могла выделиться под другой индекс. 
Делать в комплишене столько сложной работы – плохая идея. Скорее всего это и есть причина остающегося слоя с градиентом

2023-02-10 19:30 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +                self.animationLayers.removeAll()
очень странно, изображение одно загрузилось, а слои все удаляются

Операция не страшная, так как на пустом масиве и удалять нечего, но бессмысленная

2023-02-10 19:31 UTC, ABashkirova commented
Не работает функция share :
<img width="866" alt="Снимок экрана 2023-02-10 в 20 30 28" src="https://user-images.githubusercontent.com/20269264/218169987-df8de882-7257-4b3b-a994-ca130b8cc76b.png">
<img width="394" alt="Снимок экрана 2023-02-10 в 20 30 39" src="https://user-images.githubusercontent.com/20269264/218169928-89b9671a-0af5-4a95-bdc3-65690c8118c0.png">

Лайк сбрасывается:
![RocketSim_Recording_iPhone_11_Pro_2023-02-10_20 33 46](https://user-images.githubusercontent.com/20269264/218170431-5602ad1d-421c-4e5a-9cfa-843764b58efd.gif)

Подвисший градиент:
<img width="394" alt="Снимок экрана 2023-02-10 в 20 33 26" src="https://user-images.githubusercontent.com/20269264/218170462-e0bc87cc-bd7e-4f44-813b-9ee0366e0c49.png">

2023-02-10 19:51 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListService.swift
> +        task.resume()
похоже я удалил на другой строчке, а здесь пропустил

2023-02-10 20:05 UTC, IBDesignable commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    var photos: [Photo] = []
Тут добавлю, что это может происходить из-за двух причин:
- хранение двух списков, которые в какой-то момент перестали быть одинаковыми (у тебя как раз две копии, но по коду вроде бы ты в нужных местах их синхронизируешь)
- захват ссылочного типа в замыкании может давать такие аффекты
- задубленный вызов установки фетча (тоже вроде бы нет)

2023-02-10 22:34 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    var photos: [Photo] = []
Похоже причина в том, что изображение ты выставляешь на прямую изображению внутри кнопки. Для кнопок есть специальный метод setImage

Иначе кнопка так себе сохраняет настройку 


https://developer.apple.com/documentation/uikit/uibutton/1623997-setimage


At a minimum, always set an image for the normal state when associating images to a button. If you don’t specify an image for the other states, the button uses the image associated with normal. If you don’t specify an image for the normal state, the button uses a system value.

2023-02-11 07:13 UTC, DmitriiMM commented on ImageFeed/SingleImage/SingleImageViewController.swift
>      var image: UIImage! {
Александра, я могу здесь обсуждать с вами решения или принципиально задавать вопросы именно наставникам?
В данном случае я заменил на activityItems: [imageView.image], и теперь кнопка share работает. Но вы написали "функция сломана" и я сомневаюсь в своем решении. Кажется, что мое решение может не покрыть какие-то крайние случаи.

2023-02-11 08:27 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        animationLayers.insert(gradientForCell)
<img width="772" alt="Снимок экрана 2023-02-11 в 12 23 34" src="https://user-images.githubusercontent.com/86566994/218248285-492feabd-859a-4827-9c6d-7608f8b1e706.png">

Не понял ваш вопрос. Строка animationLayers.insert(gradientForCell) есть в учебнике, но объяснения для чего она там нет. Честно, не смог понять для чего это сделано, без создания animationLayers вроде бы работает все так же. Но я решил оставить по рекомендации учебника

2023-02-11 09:51 UTC, IBDesignable commented on ImageFeed/SingleImage/SingleImageViewController.swift
>      var image: UIImage! {
Дмитрий, прошу исключить дальнейший диалог и задавать вопросы наставнику. К сожалению, студентов слишком много, чтобы поддерживать здесь диалог. Предыдущий раз был исключением, прошу понять. 

Но на вопрос отвечу: 
 activityItems: [imageView.image] – решение не очень, потому что является заплаткой и костылем. По-хорошему у экрана должна быть модель данных (раньше это было свойство Image). Но то, как спроектирован экран не оставляет нам вариантов. 

Можно оставить твое решение, но дополнительно избавиться от image, либо попробовать похожее, но через image:

```swift
self.imageView.kf.setImage(with: url) { [weak self] result in
                UIBlockingProgressHUD.dismiss()
                guard let self = self else { return }
                switch result {
                case .success(let imageResult):
                    self.image = imageResult.image
```
заменить последнюю строчку, таким образом переиспользуется свойство image и не будет дублирующего кода с rescaleAndCenterImageInScrollView. 

Надо стараться приводить экран к консистентному виду, чтобы источником изображения была одна переменная/модель – навык непростой, надо нарабатывать. Со временем наработается, нужно больше читать чужого кода (такое сложно организовать пока не работаешь, но иметь ввиду стоит).  У тебя все получится, будь внимателен и не стесняйся задавать вопросы Наставникам :)

2023-02-11 11:53 UTC, DmitriiMM commented on ImageFeed/SingleImage/SingleImageViewController.swift
>      var image: UIImage! {
Ахахаха) простите))

2023-02-11 12:03 UTC, DmitriiMM commented on ImageFeed/Profile/ProfileViewController.swift
> +        authViewController.modalPresentationStyle = .fullScreen
Честно говоря, совсем не могу придумать что здесь можно добавить( 
И, скорее всего, проблема при быстром скроле ушла, пока я корректировал код по комментариям выше.

2023-02-11 12:15 UTC, DmitriiMM commented on ImageFeed/Profile/ProfileViewController.swift
> +    let gradientChangeAnimation = CABasicAnimation(keyPath: "locations")
Аналогично комментарию выше. Слой градиента больше не остается.

2023-02-11 13:33 UTC, DmitriiMM commented on ImageFeed/SingleImage/SingleImageViewController.swift
>      var image: UIImage! {
Очень жаль что нужно исключить дальнейший диалог. Здесь значительно быстрее получаю ответы и плюс обсуждение идет предметно. А учитывая, что осталась последняя попытка отправки на ревью, так вообще не хочется отправлять пока вопрос каждого комментария не будет согласован)) Извиняюсь, что продолжаю переписываться. Читать как фидбек к процессам обучения)

2023-02-11 19:28 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        animationLayers.insert(gradientForCell)
Спасибо за уточнение!

Постараюсь донести твой фидбек до авторов и сама узнаю, зачем нужны. 

Но смотри: загруженное изображение в одной ячейке, еще не значит, что остальные загрузились и удалять их получается смысла нет, ведь мы не можем убедиться что все изображения прогрузились.

2023-02-11 19:45 UTC, ABashkirova reviewed
Последние доработки – супер :) очень рада что теперь все летает)

Если будет время еще можно заняться двумя багами верстки: 
У табов нет подписей в фигме (кажется в учебнике была опечатка на этот счет), и в веб-вью прогрессВью перекрывает контент (в фигме тоже не так). 

<img width="394" alt="Снимок экрана 2023-02-11 в 21 41 58" src="https://user-images.githubusercontent.com/20269264/218278126-5cd135ec-ac0a-4138-841c-48576ab10681.png">


<img width="394" alt="Снимок экрана 2023-02-11 в 21 43 45" src="https://user-images.githubusercontent.com/20269264/218278124-4464d840-6d27-4b7b-8027-1284843d876a.png">

2023-02-11 19:45 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +        gradientChangeAnimation.toValue = [0, 0.8, 1]
так как метод configLoadingGradient может вызываться несколько раз, я думаю в качестве рефактринга можно еще оптимизировать и перенести это при создании gradientChangeAnimation

```swift
private lazy var gradientChangeAnimation: CAAnimation = {
 let gradientChangeAnimation =  CABasicAnimation(keyPath: "locations") 
 gradientChangeAnimation.duration = 1.0
         gradientChangeAnimation.repeatCount = .infinity
         gradientChangeAnimation.fromValue = [0, 0.1, 0.3]
         gradientChangeAnimation.toValue = [0, 0.8, 1]
   return gradientChangeAnimation
}()
```

просто потом будешь добавлять анимацию к слою сразу.

2023-02-11 19:45 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
>      var gradientLoading = CAGradientLayer()
Видеть здесь градиент – стало гораздо легче, чем в контроллере, спасибо :)

2023-02-11 19:45 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        cell.contentView.bringSubviewToFront(cell.imageCell)
ого! неочевидное решение :) но полагаю рабочее :)

молодец :) редко когда пользуюсь этими методами, круто что нашел как применить)

2023-02-11 19:45 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +        let ac = UIActivityViewController(activityItems: [item], applicationActivities: nil)
👍🏻

2023-02-11 19:45 UTC, ABashkirova commented on ImageFeed/SingleImage/SingleImageViewController.swift
> +        let ac = UIActivityViewController(activityItems: [item], applicationActivities: nil)
тут кстати, я замечу, кейс, что изображение может же не прогрузиться, и тогда нечего будет шарить, а кнопка всегда активна и нажимаема 


Эта обработка не будет вызывать системное окно – это круто. Также можно было бы кнопку блочить, пока изображения нет, но такого состояния в фигме нет, поэтому этого решения более чем достаточно

2023-02-11 19:45 UTC, ABashkirova commented on ImageFeed/ImagesList/ImagesListCell.swift
> +            likeButtonCell.setImage(UIImage(named: "NoActive"), for: .normal)
Кстати, замечу, что даже мне не очевидно было, что это может приводить к такому багу :) 

Но еще раз иллюстрирует эпизод где надо решать задачу правильными инструментами, а не обходными путями :)

2023-02-11 21:36 UTC, DmitriiMM commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        animationLayers.insert(gradientForCell)
Ну да, логично. Понял. Скрин относится к экрану профиля. Так что там такой подход, получается, уместен.

2023-02-11 21:49 UTC, DmitriiMM commented
Спасибо большое за вашу работу! Очень рад что именно вам, Александра, достался мой проект на проверку. Подробнейшие комментарии, уйма советов. Обязательно все доделаю, на что еще указали. 
Лучший ревьювер! Спасибо!

2023-02-12 09:18 UTC, merged